#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
if [ -z "${DOTFILES}" ]; then
    echo "No DOTFILES variable was set";
    exit 1;
fi

mode=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)
            mode="$2"; shift 2 ;;
        --mode=*)
            mode="${1#*=}"; shift ;;
        *)
            echo "Usage: $0 [--mode PRESET]";
            exit 1 ;;
    esac
done

if [[ -n "$mode" ]]; then
    preset_file="$DOTFILES/presets/$mode"
    if [[ -f "$preset_file" ]]; then
        STOW_FOLDERS=$(paste -sd, "$preset_file")
    else
        echo "Unknown mode: $mode"
        exit 1
    fi
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
