#!/usr/bin/env bash

# alias aoeu="setxkbmap us"
# alias oeui="setxkbmap dvorak"
# alias htns="setxkbmap real-prog-dvorak"
# alias gcrl="setxkbmap real-prog-dvo-k"

# alias asdf="setxkbmap dvorak"
# alias sdfg="setxkbmap real-prog-dvorak"

#alias lkj="setxkbmap real-prog-dvorak"
#alias snth="setxkbmap us"

alias files=ranger

alias rm-confirm="/bin/rm -irv"
alias rm='echo "rm is disabled, use rm-confirm or trash or /bin/rm instead."'

alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
#alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
#alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
#alias kill_netflix="pkill -9 GIBBON_MAIN"
alias work="cd ~/work"

alias python="python3"
#alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias zshrc="$VIM $DOTFILES/.zsh_profile"
#alias etc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.tmux.conf"
alias rLoadShell="dotFileInstall && source ~/.zshrc"
#alias evrc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.vimrc"
#alias enrc="nvim $DOTFILES/awesome-streamerrc/ThePrimeagen/init.vim --cmd \"cd $DOTFILES/awesome-streamerrc/ThePrimeagen/init.vim\""
alias yolo="git push origin master --force --no-verify"
alias i3rc="nvim $XDG_CONFIG_HOME/i3/i3config"
#alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/run"

# Wayland/X11 detection for clipboard aliases
if [ "$XDG_SESSION_TYPE" = "wayland" ] || [ -n "$WAYLAND_DISPLAY" ]; then
  alias xclip='wl-copy'
  alias xsel='wl-paste'
  alias xsc='wl-copy'
  alias cclip='wl-copy'
  alias pclip='wl-paste'


  # Direct hyprctl commands (these should work)
  alias aoeu="hyprctl switchxkblayout at-translated-set-2-keyboard 2" # us
  alias htns="hyprctl switchxkblayout at-translated-set-2-keyboard 1" # real-prog-dvorak
  alias gcrl="hyprctl switchxkblayout at-translated-set-2-keyboard 0" # real-prog-dvo-k

  alias asdf="hyprctl switchxkblayout at-translated-set-2-keyboard 0" # dvorak
  alias sdfg="hyprctl switchxkblayout at-translated-set-2-keyboard 1" # real-prog-dvorak

  # Script-based cycling (make sure script is executable)
  alias kb-cycle="$HOME/.local/scripts/hypr-kb-switch cycle"

  # alias aoeu="hyprctl switchxkblayout at-translated-set-2-keyboard 2" # us
  # alias oeui="hyprctl switchxkblayout at-translated-set-2-keyboard 3" # dvorak (if added)
  # alias htns="hyprctl switchxkblayout at-translated-set-2-keyboard 1" # real-prog-dvorak
  # alias gcrl="hyprctl switchxkblayout at-translated-set-2-keyboard 0" # real-prog-dvo-k (default)

else
  alias xsc="xclip -selection clipboard"
  alias cclip="xclip -selection clipboard"
  alias pclip="xclip -selection clipboard"

  alias aoeu="setxkbmap us"
  alias oeui="setxkbmap dvorak"
  alias htns="setxkbmap real-prog-dvorak"
  alias gcrl="setxkbmap real-prog-dvo-k"

  alias asdf="setxkbmap dvorak"
  alias sdfg="setxkbmap real-prog-dvorak"
fi

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"

# alias xsc="xclip -selection clipboard"
# alias cclip="xclip -selection clipboard"
# alias pclip="xclip -selection clipboard"

#alias timeplus="~/dotfiles/apps/time_plus_30"
#alias echotime="~/dotfiles/apps/echo_time"
#alias livestream_screenkey="screenkey -s large --scr 2 -p bottom --geometry 1210x300+712+810";
#alias yt_screenkey="screenkey -s large --scr 1 -p bottom --geometry 510x300+1412+850";

alias mynpm='rm ~/.npmrc'
